import Head from "next/head";
import Image from "next/image";
import styles from "../src/stylesheets/Home.module.css";
import Login from "../src/components/common/login";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Basic Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>User Login</h1>
        <Login />
      </main>
    </div>
  );
}
